library switch: fix switch on mobile
rero/rero-ils-ui pull request #1059
Opened 2023-10-10 13:21 UTC by Garfield-fr

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2023-10-11 08:23 UTC, jma requested changes

2023-10-11 08:23 UTC, jma commented on projects/admin/src/app/menu/service/library-switch-menu-event.service.ts
> +    console.log(event, event.getExtra('id'));
To remove

2023-10-12 06:12 UTC, zannkukai approved these changes

2023-10-12 06:17 UTC, jma approved these changes

2023-10-26 07:04 UTC, PascalRepond approved these changes

2023-10-31 10:44 UTC, merged