ill requests: sort by descending date
rero/rero-ils-ui pull request #1070
Opened 2023-10-31 13:11 UTC by PascalRepond

* Sorts ILL Requests by descending created-date in the ApiService.
* Displays the ILL 'request date' in the pro patron view details.

2023-10-31 15:09 UTC, Garfield-fr requested changes

2023-10-31 15:09 UTC, Garfield-fr commented on projects/admin/src/app/api/ill-request-api.service.ts
> +                  undefined, filters, BaseApi.reroJsonheaders, '-created')
Add parameter into the function like this `getByPatronPid(patronPid: string, filters?: {[key: string]: string}, order: string = '-created')`
and into the fonction getRecords `BaseApi.reroJsonheaders, $order`

2023-10-31 15:09 UTC, Garfield-fr commented on projects/public-search/src/app/api/ill-request-api.service.ts
> +    return this._recordService.getRecords('ill_requests', query, page, itemsPerPage, undefined, undefined, headers, '-created');
same here

2023-11-08 08:23 UTC, zannkukai approved these changes

2023-11-09 07:08 UTC, jma approved these changes

2023-11-09 07:34 UTC, merged