chore(menu): add query params on some route
rero/rero-ils-ui pull request #1136
Opened 2024-03-06 06:42 UTC by Garfield-fr

To avoid redirection if the default settings are not present, they are added directly to the menu items.

2024-03-06 07:37 UTC, PascalRepond requested changes

2024-03-06 07:37 UTC, PascalRepond commented on projects/admin/src/app/menu/menu-definition/menu-app.ts
> +          library: '$currentLibrary'
Filter name is 'owner_library'

2024-03-06 07:45 UTC, PascalRepond approved these changes

2024-03-11 09:07 UTC, lauren-d approved these changes

2024-03-13 09:35 UTC, merged