files: add upload file support
rero/rero-ils-ui pull request #1137
Opened 2024-03-13 10:49 UTC by jma

* Adds files list and file uploads on the professionnal views.
* Adds icons depending of the mime types.

2024-03-21 14:22 UTC, Garfield-fr requested changes
Please reformat your code with minimun 120 chars.

2024-03-21 14:22 UTC, Garfield-fr commented on projects/admin/src/app/routes/route-tool.service.ts
> +    console.log(record, recordType);
remove this

2024-03-21 14:22 UTC, Garfield-fr commented on projects/admin/src/app/service/resources-files.service.spec.ts
> +import { TestBed } from '@angular/core/testing';
missing copyright

2024-03-21 14:22 UTC, Garfield-fr commented on projects/admin/src/app/service/resources-files.service.ts
> +import { HttpClient, HttpResponse } from "@angular/common/http";
missing copyright

2024-03-21 14:22 UTC, Garfield-fr commented on projects/shared/src/lib/modules/prime-ng-import/prime-ng-import.module.ts
> + * Copyright (C) 2019-2022 RERO
2024

2024-03-25 08:45 UTC, lauren-d approved these changes

2024-04-11 12:24 UTC, merged