circulation : toasr message when item goes in transit
rero/rero-ils-ui pull request #339
Opened 2020-08-17 10:17 UTC by zannkukai

When an item is checked-in and goes in transit, add a toastr message to
informs user about this spec.

Co-Authored-by: Renaud Michote <renaud.michotte@gmail.com>

## How to test?

- Checkin an item to goes in transit. Use the SCENARIO B

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Extracted translations?

2020-08-19 04:43 UTC, iGormilhit approved these changes
Commit message approved.

2020-08-24 10:58 UTC, sebastiendeleze requested changes

2020-08-24 10:58 UTC, sebastiendeleze commented on projects/admin/src/app/circulation/checkin/checkin.component.ts
> +        console.log(item);
remove `console.log` call

2020-08-25 12:26 UTC, sebastiendeleze approved these changes

2020-08-25 12:27 UTC, merged