ipublic search: fix contribution facet
rero/rero-ils-ui pull request #354
Opened 2020-09-01 09:26 UTC by rerowep

* Fixes the contribution facet.

Co-Authored-by: Peter Weber <peter.weber@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on `rero-ils#<xx>`'s PR(s):

* rero/rero-ils#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Extracted translations?

2020-09-01 11:54 UTC, iGormilhit requested changes
Translations files should not be update in this commit. It may create conflicts with weblate. Moreover, I think that the facet will still be named "author" on the web interface.

https://tree.taiga.io/project/rero21-reroils/us/1490?milestone=269576:
> The "author" facet stays as is. It joins values from MEF and from the authors present only in documents. MEF values are multilingual.


For the commit message:

```
search: fix contribution facet

* Fixes the contribution facet of the public interface after the implementation of the contribution field that takes place of the authors field.
``

2020-09-02 07:57 UTC, AoNoOokami approved these changes

2020-09-03 11:50 UTC, lauren-d requested changes

2020-09-03 21:00 UTC, rerowep commented on projects/public-search/src/assets/rero-ils-ui/public-search/i18n/de.json
> +  "contribution__it": "Beitrag",
Ok I added them, but there where not present there.

2020-09-03 22:22 UTC, lauren-d approved these changes

2020-09-04 07:11 UTC, zannkukai approved these changes

2020-09-04 12:17 UTC, benerken approved these changes

2020-09-07 10:22 UTC, iGormilhit approved these changes

2020-09-07 10:23 UTC, merged