circulation: add patron circulation statistics
rero/rero-ils-ui pull request #394
Opened 2020-10-16 16:31 UTC by zannkukai

This commit adds some statistics on tabs into the patron circulation
detail page. Available statistics are for 'CI/CO', 'pickup' and
'pending' tabs.

Closes rero/rero-ils#1278

Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on `rero-ils#<xx>`'s PR(s):

* rero/rero-ils#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Extracted translations?

2020-10-26 14:13 UTC, Garfield-fr commented on projects/admin/src/app/circulation/patron/main/main.component.html
> +          <span *ngIf="this.patronCirculationStatistics.loans > 0" class="badge badge-info font-weight-normal">
Why do you hide the badge if the result is 0? The user will not click if the total is 0

2020-10-26 14:13 UTC, Garfield-fr commented on projects/admin/src/app/circulation/patron/main/main.component.html
> +          <span *ngIf="this.patronCirculationStatistics.pickup > 0" class="badge badge-info font-weight-normal">
same here

2020-10-26 14:13 UTC, Garfield-fr commented on projects/admin/src/app/circulation/patron/main/main.component.html
> +          <span *ngIf="this.patronCirculationStatistics.pending > 0" class="badge badge-info font-weight-normal">
same here

2020-10-28 06:52 UTC, iGormilhit requested changes
Commit message proposition: 
```
circulation: add counter on tabs 

This commit adds counter on tabs of the patron circulation detail page.
Available counter are for checkin/checkout, pickup and pending tabs.

Closes rero/rero-ils#1278
Closes rero/rero-ils#1281
```

2020-10-28 08:07 UTC, AoNoOokami commented
Please add the related rero-ils PR in the description

2020-10-28 10:25 UTC, closed without merging