patron_types: adapts detail view for limits
rero/rero-ils-ui pull request #399
Opened 2020-10-23 14:32 UTC by zannkukai

Adapts the patron type resource detail view to include the display of
limits.

Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

![image](https://user-images.githubusercontent.com/10031585/97016722-5fde4780-154d-11eb-8991-d1020df5360a.png)

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?

2020-10-26 06:59 UTC, iGormilhit requested changes
Commit proposition:
```
patron_types: display restrictions on detailed view 

Adapts the patron type detailed view to display the circulation
restrictions.
```

2020-10-26 07:57 UTC, Garfield-fr approved these changes

2020-10-26 07:57 UTC, Garfield-fr commented on projects/admin/src/app/record/detail-view/patron-types-detail-view/patron-types-detail-view.component.html
> +                <dt class="offset-1 col-11 label-title"translate>Exceptions</dt>
Missing space before `translate`

2020-10-26 07:57 UTC, Garfield-fr commented on projects/admin/src/app/record/detail-view/patron-types-detail-view/patron-types-detail-view.component.html
> +              <dt class="offset-1 col-lg-2 col-sm-4 label-title"translate>General limit</dt>
Missing space before `translate`

2020-10-26 07:57 UTC, Garfield-fr commented on projects/admin/src/app/record/detail-view/patron-types-detail-view/patron-types-detail-view.component.html
> +                <dt class="offset-1 col-lg-2 col-sm-4 label-title"translate>Library limit</dt>
Missing space before `translate`

2020-10-26 07:57 UTC, Garfield-fr commented on projects/admin/src/app/record/detail-view/patron-types-detail-view/patron-types-detail-view.component.html
> +              <dt class="offset-1 col-lg-2 col-sm-4 label-title"translate>Limit</dt>
Missing space before `translate`

2020-10-26 07:57 UTC, Garfield-fr commented on projects/admin/src/app/record/detail-view/patron-types-detail-view/patron-types-detail-view.component.html
> +              <dt class="offset-1 col-lg-2 col-sm-4 label-title"translate>Limit</dt>
Missing space before `translate`

2020-10-28 06:44 UTC, iGormilhit approved these changes
Commit message approved.

2020-11-02 11:19 UTC, merged