Zan #1799 refactoring circulation infos
rero/rero-ils-ui pull request #405
Opened 2020-10-28 16:09 UTC by zannkukai

The message return by the backend when a user is blocked has changed.
This commit adapts the UI to this change and display the error message
returned by the backend directly.
This commit also adds counter on tabs of the patron circulation detail
page. Available counter are for checkin/checkout, pickup and pending
tabs.

Small correction on the template detail view.

Closes rero/rero-ils#1278
Closes rero/rero-ils#1281

Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## Dependencies

 * https://github.com/rero/rero-ils/tree/US1643-borrow-limits

## How to test?

![image](https://user-images.githubusercontent.com/10031585/97463089-aeba2180-193f-11eb-87c8-bc90b218636a.png)

* Use the professional interface to block a user. 
* Go in the circulation interface for this patron ; you should see this message in red (see screenshot)
* Unblock the patron
* Define some (small) limits on a patron_type and assign this patron_type to this patron
* Do some checkout operation until the define limit is reached.
* Reload the circulation interface for this patron : you should see a message in red.

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?

2020-11-02 08:01 UTC, Garfield-fr commented
I consider the message system to be too large. Soon you don't see the important part.

2020-11-02 12:09 UTC, Garfield-fr commented on projects/admin/src/app/circulation/patron/card/card.component.html
> +      <strong class="alert-heading">{{ note.type.toString() | translate }}</strong>
`<strong class="alert-heading" translate>{{ note.type.toString() }}</strong>`

2020-11-02 12:09 UTC, Garfield-fr commented on projects/admin/src/app/record/detail-view/template-detail-view/template-detail-view.component.html
>          </dd>
`<dd id="template-description" [ngClass]="ddCssClass" [innerHtml]="record.metadata.description | nl2br">`

2020-11-02 12:09 UTC, Garfield-fr commented on projects/admin/src/app/service/patron.service.ts
> +    const url = `/api/patrons/${patronPid}/circulation_informations`;
Inject `ApiService` to `PatronService` and use `[this._apiService.getEndpointByType('patrons'), patronPid, 'circulation_informations'].join('/')`

2020-11-02 13:53 UTC, zannkukai commented on projects/admin/src/app/circulation/patron/card/card.component.html
>              </a>
at UCL, we have some students (mainly from Asia or Africa) without any firstname.
Asked the question to PO to found a solution

2020-11-02 15:55 UTC, AoNoOokami requested changes
When I create a patron type to add limits, clicking on one of the limit toggle switch activates `Yearly subscription`. I couldn't test further because of that.

![limits](https://user-images.githubusercontent.com/28982829/97889097-38953080-1d2c-11eb-8541-d72f51da55fd.png)

2020-11-02 15:55 UTC, AoNoOokami commented on projects/admin/src/app/circulation/patron/card/card.component.ts
> +  getBoootstrapColor(level: string): string {
There are 3 `o` in the method definition

2020-11-03 07:55 UTC, AoNoOokami commented
> When I create a patron type to add limits, clicking on one of the limit toggle switch activates `Yearly subscription`. I couldn't test further because of that.
> 
> ![limits](https://user-images.githubusercontent.com/28982829/97889097-38953080-1d2c-11eb-8541-d72f51da55fd.png)

Due to the wrong version of ng-core.

2020-11-03 08:55 UTC, AoNoOokami approved these changes

2020-11-04 06:06 UTC, iGormilhit approved these changes
Commit message approved.

2020-11-04 21:13 UTC, merged