request: preserver request order.
rero/rero-ils-ui pull request #407
Opened 2020-10-29 15:24 UTC by zannkukai

On the item detailed view, you can display requests made by user about
this item. The request list should be sorted by creation date but
wasn't. This commit corrects this problem.

Closes rero/rero-ils#1314

Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?

2020-11-02 05:24 UTC, Garfield-fr commented on projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.html
> +        {{ record.metadata.item_type.pid | getRecord:'item_types':null:'name' | async }}
Why `null` ?

2020-11-02 05:24 UTC, Garfield-fr commented on projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.html
> +          {{ record.metadata.document.pid | getRecord:'documents':null :'title' | async | mainTitle }}
Why `null` ?

2020-11-02 05:24 UTC, Garfield-fr commented on projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.html
> +          {{ location.metadata.library.pid | getRecord: 'libraries': null: 'name' | async}}
Why `null` ?
Missing space after `async`

2020-11-02 05:24 UTC, Garfield-fr commented on projects/admin/src/app/record/detail-view/item-detail-view/item-transactions/item-transactions.component.html
> +        <b>{{ requestedBy.length | i18nPlural: {'=1': 'Request', 'other': 'Requests'} | translate }}</b>
`{ '=1': 'Request' | translate , 'other': 'Requests' | translate }` ?

2020-11-02 06:42 UTC, iGormilhit requested changes
Commit message proposition:

```
item: keep request order

The item detailed view displays the requests made by users. The request
list should be sorted by creation date but isn't. This commit fix this
issue.

Closes rero/rero-ils#1314
```

2020-11-02 07:32 UTC, zannkukai commented on projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.html
> +        {{ record.metadata.item_type.pid | getRecord:'item_types':null:'name' | async }}
oups

2020-11-02 07:55 UTC, Garfield-fr approved these changes

2020-11-03 08:24 UTC, AoNoOokami requested changes

2020-11-03 08:24 UTC, AoNoOokami commented on projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.html
> +        <ng-container *ngIf="location">
Is this change described in the commit message?

2020-11-03 15:26 UTC, AoNoOokami approved these changes

2020-11-03 15:36 UTC, merged