serials: new service to display late/claimed issues
rero/rero-ils-ui pull request #425
Opened 2020-11-09 15:40 UTC by BadrAly

A new item "Late issues" in the Acquisition menu is added
to display late and claimed issues filtered by library and
location and issue status.

Co-Authored-by: Johnny Mariéthoz <Johnny.Mariethoz@rero.ch>
Co-Authored-by: Aly Badr <aly.badr@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on `rero-ils#<xx>`'s PR(s):

* rero/rero-ils#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?

2020-11-10 12:01 UTC, lauren-d requested changes

2020-11-10 12:01 UTC, lauren-d commented on projects/admin/src/app/service/holdings.service.ts
> +  getIcon(status: IssueItemStatus): string {
missing docstrings

2020-11-10 12:01 UTC, lauren-d commented on projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.ts
> +    private _holdingService: HoldingsService,
missing param in docstrings

2020-11-10 12:24 UTC, lauren-d approved these changes

2020-11-10 16:34 UTC, zannkukai commented on projects/admin/src/app/record/brief-view/issues-brief-view/issues-brief-view.component.ts
> +/** reference to IssueItemStatus */
COSMETIC : docstring indentation

2020-11-10 16:35 UTC, zannkukai commented on projects/admin/src/app/record/brief-view/issues-brief-view/issues-brief-view.component.ts
> +  @Input()
COSMETIC : My point of view :: for attributes, I prefer docstring on single line

2020-11-10 16:37 UTC, zannkukai commented on projects/admin/src/app/record/detail-view/holding-detail-view/serial-holding-detail-view/serial-holding-detail-view.component.ts
> +   * Make the method getIcon available here
COSMETIC : missing `@param` docstring and `@return`.
Proposition : 
```
/**
 * Make the method getIcon from holdingService available
 * @param status: the item status
 * @return: the font-awsome icon to use
```

2020-11-10 16:39 UTC, zannkukai commented on projects/admin/src/app/service/holdings.service.ts
> +   * Return issue icon
Not need this first line ;-) the second one is better and suffisant.

2020-11-10 16:39 UTC, zannkukai approved these changes
> 👍 good job for a first Angular PR !!

credit goes to @jma

2020-11-11 06:16 UTC, iGormilhit approved these changes
Commit message approved.

2020-11-11 09:31 UTC, AoNoOokami approved these changes

2020-11-11 09:37 UTC, benerken commented
Great Job !

**Enhancement (To do later)**

- In the "Late Issues" result screen, there is a search box. As a librarian, I would like to search on journal title in order to get all late issues linked to a journal.  I know there is a link to the document, where we can see holdings & issues but it could be faster to filter result in the "late issues" screen (?)  

- In the "Late Issues" result screen, add an export function in order to use this list anywhere else (in a spreadsheet, in a mail etc...)

2020-11-11 09:37 UTC, benerken approved these changes

2020-11-11 10:40 UTC, pronguen commented
- [ ] When I change the location of the holdings, the location of the item/issues is not change. It should. Rather: the location should be removed from the issue/item. Probably not linked to this PR > open an issue.
- [ ] Pro interface: it is not clear which issues are shown in the document detailed view (see image). Expected: show all issues in the receive interface, show only received issues in the document detailed view.
for document https://ilsdev.test.rero.ch/professional/records/documents/detail/1062

![image](https://user-images.githubusercontent.com/8154915/98789321-6e0fdd00-2402-11eb-9397-9178fac11f7f.png)

- [ ] Public interface: show only received issues in the document detailed view. Ideally sort issues by unit (decreasing).
- [ ] I cannot see the link to the vendor in the holdings editor.
- [ ] What means "Issue status date" in the late issues brief view, and why is this info not present in the issue detailed view? I think it is the date when the status changed. I would put this date in parenthesis just next to the status.

2020-11-12 13:06 UTC, merged