request: basic ill request management.
rero/rero-ils-ui pull request #439
Opened 2020-11-19 09:14 UTC by zannkukai

Adds basic functionalities to manage the ill requests into the
professional interface :
  * adds menu entry to list ILL requests (with faceting).
  * adds brief/detail view for ILL requests.
  * allows ILL request creation by staff members.
  * allows ILL request management (edit) by staff members.

This commit also implements an autocomplete typeahead widget on patron
resource.

Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?

2020-11-26 05:31 UTC, Garfield-fr approved these changes

2020-11-26 06:07 UTC, iGormilhit requested changes
Commit message proposition:

```
request: implement basic ILL request management

Adds basic functionalities to manage the ILL requests into the
professional interface:
  * Adds menu entry to list ILL requests (with faceting).
  * Adds brief and detail views for ILL requests.
  * Allows ILL request management (edit) by staff members.
  * Allows ILL request creation by staff members.
* Implements an autocomplete typeahead widget on patron
  resource.
```
I'm not sure with the last line. This autocomplete is used to find patrons through an editor (ie the ILL request creation form)? If so, "Implements an autocomplete typeahead widget to search for patrons in an editor select.", could be better.

2020-11-30 08:07 UTC, iGormilhit approved these changes

2020-11-30 11:15 UTC, AoNoOokami approved these changes

2020-12-07 13:54 UTC, merged