document: holdings should be grouped by libraries
rero/rero-ils-ui pull request #453
Opened 2020-12-03 13:05 UTC by Garfield-fr

* closes #1399

Co-Authored-by: Bertrand Zuchuat <bertrand.zuchuat@rero.ch>

## How to test?

- Check order on document view.

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2020-12-03 15:53 UTC, iGormilhit requested changes
Commit message minor corrections:

```
documents: group holdings by libraries

* Closes rero/rero-ils#1399.
```

2020-12-11 11:21 UTC, benerken approved these changes

2020-12-14 06:10 UTC, iGormilhit approved these changes

2020-12-14 10:11 UTC, AoNoOokami approved these changes

2020-12-15 09:25 UTC, merged