document: improve document detail view
rero/rero-ils-ui pull request #461
Opened 2020-12-08 12:39 UTC by zannkukai

* Replaces the 'duplicate' button just near other buttons.
* Update the style of duplicate button to use outline.
* Gives more spaces around abstract for a better readability.
* Gives more horizontal spaces to basic informations (useful for
document with long abstract).

Adds a specific style for item list. This style display a dotted border
between the item label and the item value.

Co-Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on `rero-ils#<xx>`'s PR(s):

* rero/rero-ils#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2020-12-09 07:10 UTC, Garfield-fr approved these changes

2020-12-09 07:10 UTC, Garfield-fr commented on projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html
> +     style="margin-right: -1.5rem"
Use `class` instead of `style`

2020-12-09 07:19 UTC, iGormilhit requested changes
Commit message proposition:

```
document: improve detailed view

* Places the 'duplicate' button with other buttons.
* Updates the duplicate button to use outline button style.
* Gives more space around abstract for a better readability.
* Gives more horizontal space for basic information (useful for document
  with long abstract).
* Adds a specific style for item list. This style displays a dotted line
  from the item label to the item value.
```

2020-12-09 07:19 UTC, iGormilhit commented on projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html
> +     style="margin-right: -1.5rem"
Not in a SCSS file?

2020-12-10 06:57 UTC, iGormilhit approved these changes

2020-12-10 08:11 UTC, AoNoOokami commented on projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html
> +     [queryParams]="{source: source, pid: pid}" class="btn btn-sm btn-outline-primary"
Should `class=` be on the following line too?

2020-12-10 21:08 UTC, merged