items: inherit holdings first call_number
rero/rero-ils-ui pull request #462
Opened 2020-12-10 08:20 UTC by BadrAly

For items, the parent holdings first
call_number is displayed when the item has no first
call_number. This call number is inherited in the
following screens :

* document, holdings and item details view.
* patron profile: loans, requests, history tabs.
* collection details view.

* Closes #1288

Co-Authored-by: Aly Badr <aly.badr@rero.ch>
Co-Authored-by: Bertrand Zuchuat <bertrand.zuchuat@rero.ch>
Co-Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on `rero-ils#<xx>`'s PR(s):

* rero/rero-ils#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-01-06 13:19 UTC, zannkukai commented on projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.ts
> +  providers: [ItemHoldingsCallNumberPipe]
Seems not yet be use in the component, should be removed (and remove import).
But it depends of the next comment (overkill component)

2021-01-06 13:19 UTC, zannkukai commented on projects/admin/src/app/record/detail-view/document-detail-view/inherited-call-numbers/inherited-call-numbers.component.ts
> +}
For me and myself, this component seems completely overkill. 
I think a Pipe should be more elegant way to do this

2021-01-11 08:34 UTC, zannkukai approved these changes

2021-01-11 13:04 UTC, pronguen commented
- [ ] The request view must be adapted (https://ilsdev.test.rero.ch/professional/circulation/requests)
- [ ] The CSV export (inventory list) must be adapted

2021-01-12 07:34 UTC, JoelleDosimont commented
- When changing manually an issue (put it in "claim" status, for example) and then perform a "quick receive" for the next issue, the call number doesn't show properly in the new issue received, but it's ok after a refresh : 
![image](https://user-images.githubusercontent.com/55576980/104283216-822e9400-54b0-11eb-8f32-de73287d5fd2.png)

2021-01-12 10:51 UTC, iGormilhit requested changes
Commit message proposition (minor changes):

```
items: inherit holdings first call_number

For items, the first call_number of the parent holdings is displayed
when the item has no first call_number. This call number is inherited in
the following views:

* Document, holdings and item details view.
* Patron profile: loans, requests, history tabs.
* Collection details view.

* Closes #1288.

Co-Authored-by: Aly Badr <aly.badr@rero.ch>
Co-Authored-by: Bertrand Zuchuat <bertrand.zuchuat@rero.ch>
Co-Authored-by: Renaud Michotte <renaud.michotte@gmail.com>
```

2021-01-13 07:23 UTC, iGormilhit approved these changes

2021-01-13 11:22 UTC, merged