item: display notifications in chronological order
rero/rero-ils-ui pull request #465
Opened 2020-12-10 09:51 UTC by zannkukai

Adds a sort criteria when we search about notifications linked to an
item. The sort criteria used is 'mostrecent'.

Closes rero/rero-ils#1549

Co-authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## Dependencies

https://github.com/rero/rero-ils/pull/1553

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2020-12-11 11:18 UTC, Garfield-fr approved these changes

2020-12-11 11:20 UTC, benerken approved these changes

2020-12-14 06:04 UTC, iGormilhit requested changes
Commit message proposition:

```
items: sort notifications in chronological order

Adds a sort criteria for notification searches linked to an item. The
used sort criteria is 'mostrecent'.

Closes rero/rero-ils#1549.
```

2020-12-14 10:10 UTC, AoNoOokami approved these changes

2020-12-15 08:51 UTC, merged