ILL requests: fix search results errors
rero/rero-ils-ui pull request #471
Opened 2020-12-14 09:20 UTC by jma

* Fixes errors when the search results of the ILL requests are displayed.

Co-Authored-by: Johnny Mariéthoz <Johnny.Mariethoz@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on `rero-ils#<xx>`'s PR(s):

* rero/rero-ils#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2020-12-14 10:04 UTC, AoNoOokami approved these changes
Cypress tests pass with this PR and https://github.com/rero/ng-core/pull/330.

2020-12-14 10:18 UTC, zannkukai approved these changes

2020-12-15 06:48 UTC, iGormilhit requested changes
Commit message title proposition:
1. `circulation: fix ILL request search results errors` or
1. `search: fix ILL request search results errors`.

Depending on your choice, update the PR title, thanks.

2020-12-15 07:09 UTC, iGormilhit approved these changes

2020-12-15 07:31 UTC, merged