geenral: remove html tags from typeahead suggestion
rero/rero-ils-ui pull request #525
Opened 2021-02-22 16:50 UTC by zannkukai

The ngx-bootstrap library doesn't allow html tags into typeahead
suggestion anymore.

Closes rero/rero-ils#1708

Co-Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-02-22 17:53 UTC, lauren-d requested changes
typo in commit message "geenral" => "general"

2021-02-23 05:30 UTC, Garfield-fr approved these changes

2021-02-23 07:43 UTC, AoNoOokami approved these changes

2021-02-23 07:44 UTC, iGormilhit requested changes
Commit proposition:

```
typeahead: remove HTML tags from suggestion

* Fixes the typeahead suggestion as the ngx-bootstrap library doesn't
  allow HTML tags into typeahead suggestion anymore.
* Closes rero/rero-ils#1708.
```

2021-02-23 08:38 UTC, lauren-d approved these changes

2021-03-03 13:16 UTC, merged