item: add new fields
rero/rero-ils-ui pull request #539
Opened 2021-03-04 06:23 UTC by Garfield-fr

* Adds new fields on item detail.
* Adds masked item on document detail view.
* Fixes a bug on holdings availability.

Co-Authored-by: Bertrand Zuchuat <bertrand.zuchuat@rero.ch>

## Dependencies

My PR depends on branch `US-1906-item-model`:

* https://github.com/rero/rero-ils/tree/US-1906-item-model

## How to test?

- Check new fields

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-03-04 15:51 UTC, zannkukai commented on projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.html
> +        <ng-container *ngIf="(callNumber | json) != ({ first: {}, second: {} } | json)">
strange but if it works ! 👍

2021-03-04 15:53 UTC, zannkukai commented on projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.html
> +          {{ record.metadata.price }}
You can use the `currency` pipe. Already use into circulation module 
```
{{ totalAmountOfFee | currency: organisation.default_currency }}
```

2021-03-04 15:54 UTC, zannkukai commented on projects/admin/src/app/record/detail-view/record-masked/record-masked.component.ts
> +        <label class="ml-1" *ngIf="withLabel">{{ (record.metadata._masked ? 'Masked' : 'No masked') | translate }}</label>
Does it OK with string extraction ?

2021-03-04 15:55 UTC, zannkukai commented on projects/admin/src/app/record/detail-view/record-masked/record-masked.component.ts
> +        <label class="ml-1" *ngIf="withLabel">{{ 'No masked' | translate }}</label>
`transalte` on label tag

2021-03-04 15:55 UTC, zannkukai commented on projects/admin/src/app/record/detail-view/record-masked/record-masked.component.ts
> +        <label class="ml-1" *ngIf="withLabel">{{ 'No masked' | translate }}</label>
same here

2021-03-04 15:56 UTC, lauren-d approved these changes

2021-03-04 15:56 UTC, lauren-d commented on projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html
> +
one blank line could be removed

2021-03-04 15:57 UTC, zannkukai requested changes
Some minor changes

2021-03-10 09:47 UTC, zannkukai approved these changes

2021-03-10 12:54 UTC, benerken commented
- [ ] If I add an URL to an item, the URL is displayed in the public view (document detailled view) but not in the profesionnal view.
See document 2000556 on ilsdev

2021-03-11 08:11 UTC, pronguen reviewed
- [ ] **[important]** The field `_masked` should be displayed only if the resource is masked. Otherwise, the information is not relevant for the librarian.
- [ ] Item detailed view: a masked resource is displayed with a green dot. It would be better to display it without label and with the same red eye. Example: 
![image](https://user-images.githubusercontent.com/8154915/110753491-ef5b6d00-8246-11eb-9539-4b5420cace0b.png)
- [ ] Holdings detailed view:
    - [ ] the "Masked" info should also be displayed for the holdings, just before the call number.
    - [ ] the "Masked" info should also be displayed for the issues, like this for instance:
    ![image](https://user-images.githubusercontent.com/8154915/110754539-3dbd3b80-8248-11eb-9ec3-9c3bc787db08.png)
- [ ] Document detailed view: the "Masked" info should be displayed also for issue items. Example: test1 and test2 are both masked:
![image](https://user-images.githubusercontent.com/8154915/110753992-8cb6a100-8247-11eb-844c-ed8efb09b5b0.png)
- [ ] The facet "library" in the organisation view does not take into account the masked resources to display the number of occurrences. *This can be done later if it requires an effort, in that case please open an issue.*

2021-03-15 14:47 UTC, benerken approved these changes

2021-03-17 06:56 UTC, merged