fees: pay only the fees of my library
rero/rero-ils-ui pull request #552
Opened 2021-03-16 16:23 UTC by jma

* Adds a library column in the fees tabs.
* Adds a dropdown button to pay all the fees related to the current
  logged user library.
* Closes #1533.

Co-Authored-by: Johnny Mariéthoz <Johnny.Mariethoz@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on `rero-ils#<xx>`'s PR(s):

* rero/rero-ils#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-03-16 18:14 UTC, zannkukai approved these changes

2021-03-16 18:14 UTC, zannkukai commented on projects/admin/src/app/circulation/patron/patron-transactions/patron-transactions.component.html
> +                  <span class="sr-only">Split button!</span>
Could be removed or renamed.

2021-03-17 06:17 UTC, jma commented on projects/admin/src/app/circulation/patron/patron-transactions/patron-transactions.component.html
> +                  <span class="sr-only">Split button!</span>
A name suggestion?

2021-03-17 07:00 UTC, Garfield-fr approved these changes

2021-03-17 07:00 UTC, Garfield-fr commented on projects/admin/src/app/circulation/patron/patron-transactions/patron-transactions.component.html
> +                <div id="dropdown-split" *dropdownMenu class="dropdown-menu"
same here with `id`

2021-03-29 06:43 UTC, sebastiendeleze requested changes

2021-03-29 06:43 UTC, sebastiendeleze commented on projects/admin/src/app/circulation/patron/patron-transactions/patron-transactions.component.ts
> +    private _userService: UserService
Add to doc block.

2021-03-29 06:43 UTC, sebastiendeleze commented on projects/admin/src/app/circulation/patron/patron-transactions/patron-transactions.component.ts
> +    }
Bad indentation and the getter should be before public methods. Moreover, I think the `public` keyword is not required as methods are public by default. 

+ the return type is missing for both methods and doc block for getter is missing.

2021-03-30 08:09 UTC, merged