Patron in multiple organisations
rero/rero-ils-ui pull request #566
Opened 2021-04-14 04:57 UTC by Garfield-fr

## Why are you opening this PR?

- to support multiple organisations

## How to test?

- Test all circulation functions in the admin interface
- Test user functions in the public interface

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-04-21 15:22 UTC, lauren-d approved these changes

2021-04-21 15:22 UTC, lauren-d commented on projects/public-search/src/app/patron-profile/patron-profile.component.ts
> +    private _userService: UserService,
missing in docstrings

2021-04-22 04:55 UTC, Garfield-fr commented on projects/public-search/src/app/patron-profile/patron-profile-fees/patron-profile-fees.component.ts
> +    private _patronProfileMenuService: PatronProfileMenuService
done on admin branch

2021-04-22 04:55 UTC, Garfield-fr commented on projects/public-search/src/app/patron-profile/patron-profile-histories/patron-profile-histories.component.ts
> +    private _patronProfileMenuService: PatronProfileMenuService
done on admin branch

2021-04-22 04:55 UTC, Garfield-fr commented on projects/public-search/src/app/patron-profile/patron-profile.component.ts
> +    private _userService: UserService,
done on admin branch

2021-04-22 05:24 UTC, iGormilhit requested changes
Could we try to improve the commit messages together?

2021-04-22 05:24 UTC, iGormilhit commented on projects/admin/src/app/app.component.scss
> + * Copyright (C) 2019 RERO
```suggestion
 * Copyright (C) 2021 RERO
```

2021-04-22 05:24 UTC, iGormilhit commented on projects/admin/src/app/circulation/services/circulation.service.ts
> + * Copyright (C) 2019 RERO
```suggestion
 * Copyright (C) 2021 RERO
```

2021-04-22 05:24 UTC, iGormilhit commented on projects/public-search/src/app/patron-profile/patron-profile-menu.service.spec.ts
> + * Copyright (C) 2021 RERO
:+1:

2021-04-22 05:34 UTC, Garfield-fr commented on projects/admin/src/app/app.component.scss
> + * Copyright (C) 2019 RERO
done on admin branch

2021-04-22 05:34 UTC, Garfield-fr commented on projects/admin/src/app/circulation/services/circulation.service.ts
> + * Copyright (C) 2019 RERO
done on admin branch

2021-04-27 08:16 UTC, zannkukai approved these changes

2021-04-27 08:16 UTC, zannkukai commented on projects/public-search/src/app/pipe/journal-volume.pipe.ts
> +    const volume = [];
cosmetic : rename with a generic name (because, we push volume info and number info). Maybe `data` ?

2021-04-27 08:16 UTC, zannkukai commented on projects/public-search/src/app/pipe/journal-volume.pipe.ts
> +  transform(journal: { volume?: string, number?: string }, separator: string = ' -- '): string {
maybe use `&mdash;` or `&ldash;` ?

2021-04-29 14:53 UTC, iGormilhit approved these changes
Commit message approved.

2021-04-29 15:10 UTC, merged