libraries: request printing
rero/rero-ils-ui pull request #606
Opened 2021-05-11 11:56 UTC by Garfield-fr

* Implements 3 new notifications.
* Customizes message by type of notifications.

Co-Authored-by: Bertrand Zuchuat <bertrand.zuchuat@rero.ch>

## Why are you opening this PR?

- Adds 3 new notifications

## Dependencies

My PR depends PR(s):

* https://github.com/rero/rero-ils/pull/1914

## How to test?

- Check notifications form

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-05-12 05:57 UTC, iGormilhit requested changes
A verb is missing in the commit message title.
The three kind of notifications could be listed in the commit message.

2021-05-12 08:07 UTC, zannkukai commented on projects/admin/src/app/record/custom-editor/libraries/library.component.html
> +                    <div *ngIf="setting.controls.type.value|notificationType:'patron'" class="text-secondary" translate>
add spaces before and after the '|'

2021-05-12 08:07 UTC, zannkukai commented on projects/admin/src/app/record/custom-editor/libraries/library.component.html
> +                    <div *ngIf="setting.controls.type.value|notificationType:'library'" class="text-secondary" translate>
same here

2021-05-12 08:07 UTC, zannkukai commented on projects/admin/src/app/record/custom-editor/libraries/pipe/notificationType.pipe.ts
> +  };
For me, these values should be deported into a 'Notification class model' outside of the pipe.
In few months, it shouldn't be easy to remember than this config is into this Pipe.

2021-05-12 08:14 UTC, iGormilhit approved these changes

2021-05-17 08:01 UTC, zannkukai commented on projects/admin/src/app/record/detail-view/library-detail-view/library-detail-view.component.html
> +    </dd>
same remarks, especially here where we use "offset-sm" and "offset-md"... coud be change into simpliest `col-3 offset-2` and `col-7`

2021-06-09 09:04 UTC, merged