ills: extra parenthesis on edition fields
rero/rero-ils-ui pull request #673
Opened 2021-07-14 05:16 UTC by Garfield-fr

* Improves display of published fields.
* Closes rero-ils/rero-ils-ui#2062

Co-Authored-by: Bertrand Zuchuat <bertrand.zuchuat@rero.ch>

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-07-14 07:29 UTC, zannkukai approved these changes

2021-07-14 11:24 UTC, iGormilhit requested changes
Commit message proposition (please fix formmating):

```
ill requests: removes extra parenthesis

* Improves the display of the ILL request by removing extra parenthesis in some fields.
* Closes #2062.
```

2021-07-20 15:22 UTC, lauren-d approved these changes

2021-07-22 05:34 UTC, iGormilhit approved these changes

2021-07-22 09:48 UTC, jma approved these changes

2021-07-22 10:07 UTC, merged