documents: implement all fields on the detail view
rero/rero-ils-ui pull request #679
Opened 2021-07-22 06:32 UTC by Garfield-fr

Co-Authored-by: Bertrand Zuchuat <bertrand.zuchuat@rero.ch>

## Why are you opening this PR?

- Add some fields.

## How to test?

- Add data to some fields and check the display on "Description" tab

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-07-22 06:57 UTC, iGormilhit requested changes
Commit message title proposition: `documents: display all fields on the detail view`

2021-07-22 07:04 UTC, iGormilhit approved these changes

2021-07-22 14:41 UTC, zannkukai approved these changes

2021-07-22 14:41 UTC, zannkukai commented on projects/admin/src/app/record/detail-view/document-detail-view/document-description/document-description.component.ts
> +      statements.forEach((element: any) => {
cosmetic : could be merge
```javascript
this.record.metadata.seriesStatement.forEach((element: any) => { ...});
```

2021-07-22 14:41 UTC, zannkukai commented on projects/admin/src/app/record/detail-view/document-detail-view/document-description/document-description.component.ts
> +      identified.forEach((id: any) => {
same

2021-07-22 14:41 UTC, zannkukai commented on projects/admin/src/app/record/detail-view/document-detail-view/document-description/document-description.component.ts
> +        }
```javacsript 
const idtype = (id.type === 'bf:Local') ? id.source : id.type;
```

2021-07-22 14:41 UTC, zannkukai commented on projects/admin/src/app/record/detail-view/document-detail-view/document-description/document-description.component.ts
> +    return provisions;
```typecsript
return ('provisionActivity' in this.record.metadata)
  ? this.record.metadata.provisionActivity.filter(provision => 'original_date' in provision)
  : []
```

2021-07-22 14:41 UTC, zannkukai commented on projects/admin/src/app/scss/styles.scss
> +}
could you use a `p-0` on the HTML element instead.

2021-07-22 14:41 UTC, zannkukai commented on projects/admin/src/app/scss/styles.scss
> +  background: #FFFFFF;
`transparent` instead of `white` ?

2021-07-22 14:41 UTC, zannkukai commented on projects/admin/src/app/scss/styles.scss
> +  padding-left: 20px;
```map-get($spacers, 1);``` (1, 2, 3, ... correspond to p-1, p-2, p-3, ...)

2021-07-26 07:40 UTC, sebastiendeleze approved these changes

2021-07-26 07:40 UTC, sebastiendeleze commented on projects/admin/src/app/record/detail-view/document-detail-view/document-description/document-description.component.ts
> +  constructor(public translateService: TranslateService) {}
The constructor should be before the getters

2021-07-29 11:44 UTC, benerken approved these changes

2021-09-21 08:28 UTC, merged