BNF import: disallow empty search
rero/rero-ils-ui pull request #692
Opened 2021-08-16 11:47 UTC by sebastiendeleze

* Disallows empty search to be able to search with a query in BNF
import view.
* Removes `holdings` key in documents route configuration to avoid
displaying a tab in the search view.
* Displays the title `Documents` in documents search view.

Co-Authored-by: Sébastien Délèze <sebastien.deleze@rero.ch>

2021-08-16 13:20 UTC, lauren-d approved these changes

2021-08-16 13:31 UTC, benerken approved these changes

2021-08-16 14:35 UTC, rerowep requested changes

2021-08-16 14:35 UTC, rerowep commented on projects/admin/src/app/routes/documents-route.ts
> -            deleteMessage: (pid: string): Observable<string[]> => {
The warning message for deletion of serial holdings is not correct anymore!

2021-08-17 04:15 UTC, Garfield-fr reviewed
Do not delete the holdings deletion message.

2021-08-17 07:05 UTC, zannkukai approved these changes

2021-08-17 10:47 UTC, Garfield-fr approved these changes

2021-08-17 13:30 UTC, merged