operation logs: Fix the window display if no record
rero/rero-ils-ui pull request #750
Opened 2021-11-17 11:31 UTC by Garfield-fr

Co-Authored-by: Bertrand Zuchuat <bertrand.zuchuat@rero.ch>

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-11-17 15:48 UTC, zannkukai approved these changes

2021-11-22 09:37 UTC, jma requested changes

2021-11-22 09:37 UTC, jma commented on projects/admin/src/app/record/operation-logs/operation-logs.component.html
> +                    <div class="row col">
this is not a good idea to put "row col" in the same element, put the "row" on the `li`. Can you check for other cases?

2021-11-22 09:37 UTC, jma commented on projects/admin/src/app/record/operation-logs/operation-logs.component.html
> +              <ng-container *ngIf="createRecord">
This code seems very similar to the line 47. Can you use an `ng-template`?

2021-11-23 15:44 UTC, jma approved these changes

2021-11-23 16:24 UTC, merged