general: fix error 400 bad request
rero/rero-ils-ui pull request #864
Opened 2022-06-01 13:49 UTC by Garfield-fr

* Closes rero/rero-ils#2705.
* Removes localeStorage user data.
* Updates guards that used the user localeStorage.
* Improves somes guards.
* Adds some tests for guards.

Co-Authored-by: Bertrand Zuchuat <bertrand.zuchuat@rero.ch>

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2022-06-02 06:05 UTC, jma requested changes
Some code still need to be removed such as: https://github.com/rero/rero-ils-ui/blob/972884d72ec8053be05b529f0a3a1408ef8be955/projects/admin/src/app/service/app-router-event.service.ts#L28 or `STORAGE_KEY`.

2022-06-02 07:55 UTC, zannkukai requested changes

2022-06-02 07:55 UTC, zannkukai commented on projects/admin/src/app/guard/can-access.guard.ts
> +            this._router.navigate(['/errors/403'], { skipLocationChange: true });
missing `return false`;

2022-06-02 07:55 UTC, zannkukai commented on projects/admin/src/app/guard/can-add-local-fields.guard.ts
> +        return record.metadata ? false : true;
cosmetic : I learned the `!!` operator yesterday to convert anything to boolean : https://brianflove.com/2014-09-02/whats-the-double-exclamation-mark-for-in-javascript/
So you should use  `return !!(record.metadata);` (to be tested)

2022-06-02 07:55 UTC, zannkukai commented on projects/admin/src/app/guard/can-update.guard.ts
> +          return true;
you could remove the `else` statement to return `true` by default

2022-06-02 07:55 UTC, zannkukai commented on projects/admin/src/app/guard/library.guard.ts
>            this._router.navigate(['/errors/403'], { skipLocationChange: true });
missing the `return false`

2022-06-08 07:56 UTC, benerken approved these changes

2022-06-08 09:28 UTC, zannkukai approved these changes

2022-06-08 11:50 UTC, jma approved these changes

2022-06-08 11:51 UTC, merged