application: implement permissions
rero/rero-ils-ui pull request #904
Opened 2022-10-19 10:35 UTC by Garfield-fr

* Removes the role mechanism.
* Implements the permission mechamism.

Co-Authored-by: Bertrand Zuchuat <bertrand.zuchuat@rero.ch>

## Dependencies

- https://github.com/zannkukai/rero-ils/tree/zan-expose-permissions

2022-11-02 14:35 UTC, zannkukai requested changes
Sorry for all my remarks. But it's a huge and 👏  thx

2022-11-02 14:35 UTC, zannkukai commented on projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html
> +        [customClass]="showhideLocalFieldsTab"
why not use this condition into the `*ngIf` ?
Additionally the name of the function could be more elegant and return a boolean value

2022-11-02 14:35 UTC, zannkukai commented on projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.ts
> +
See remarks above (into the related template file)

2022-11-02 14:35 UTC, zannkukai commented on projects/admin/src/app/record/detail-view/document-detail-view/holdings/holdings.component.ts
> +
same

2022-11-02 14:35 UTC, zannkukai commented on projects/admin/src/app/record/detail-view/holding-detail-view/serial-holding-detail-view/serial-holding-detail-view.component.html
> +              <i class="fa fa-file-text"></i>
I think this icon was especially choose by PO, same for `fa-pencil` below (you replaced by `fa-plus`)

2022-11-02 14:35 UTC, zannkukai commented on projects/admin/src/app/record/detail-view/holding-detail-view/serial-holding-detail-view/serial-holding-detail-view.component.html
> +  <tab id="holding-local-field-tab" tabOrder="3" [customClass]="showhideLocalFieldsTab">
`*ngIf` or your `[permissions]` directive (seems better)?

2022-11-02 14:35 UTC, zannkukai commented on projects/admin/src/app/record/detail-view/holding-detail-view/serial-holding-detail-view/serial-holding-detail-view.component.ts
> +
same + same = same^2

2022-11-02 14:35 UTC, zannkukai commented on projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.ts
> +
same

2022-11-02 14:35 UTC, zannkukai commented on projects/admin/src/app/record/detail-view/item-detail-view/item-transactions/item-transactions.component.ts
> +
same

2022-11-02 14:35 UTC, zannkukai commented on projects/admin/src/app/record/detail-view/local-field/local-field.component.ts
> +
same

2022-11-02 14:35 UTC, zannkukai commented on projects/admin/src/app/record/detail-view/patron-detail-view/patron-detail-view.component.ts
> +    return PERMISSIONS;
same or missing docstring

2022-11-02 14:35 UTC, zannkukai commented on projects/admin/src/app/record/detail-view/permission-detail-view/permission-detail-view.component.html
> +      <small id="filterInfo" class="form-text text-muted">Enter a part of the permission name to filter the list.</small>
`id` attribute could be removed

2022-11-02 14:35 UTC, zannkukai commented on projects/admin/src/app/record/detail-view/permission-detail-view/permission-detail-view.component.html
> +                    [ngClass]="{'text-success': permissionsByRoles[role][permission], 'text-danger': !permissionsByRoles[role][permission]}">
As mentionned this morning, a third value is possible.
In such case (more than 2 choices), it's more readable if each class is on a separate line (my opinion)

2022-11-02 14:35 UTC, zannkukai commented on projects/admin/src/app/record/detail-view/permission-detail-view/permission-detail-view.component.scss
> +}
move this into the `table` section (as `th`)

2022-11-02 14:35 UTC, zannkukai commented on projects/admin/src/app/record/detail-view/permission-detail-view/permission-detail-view.component.spec.ts
> +/*
Nothing is tested, could be removed

2022-11-02 14:35 UTC, zannkukai commented on projects/admin/src/app/record/operation-logs/operation-logs-dialog/operation-logs-dialog.component.ts
> +
same (next I wrote a joke to not be too redundant)

2022-11-02 14:35 UTC, zannkukai commented on projects/admin/src/app/service/app-initializer.service.ts
> +        if (user.isAdminUiAccess) {
hasAdminUIAccess as previously suggested

2022-11-02 14:35 UTC, zannkukai commented on projects/shared/src/lib/class/user.ts
> +  get isAdminUiAccess(): boolean {
`hasAdminUIAccess` ?

2022-11-02 14:35 UTC, zannkukai commented on projects/shared/src/lib/class/user.ts
> +    return this.patrons?.some((patron: IPatron) => 'patron' in patron);
don't you have an enum class to list all PatronRole ? Should be better than use 'patron' string here

2022-11-02 14:35 UTC, zannkukai commented on projects/shared/src/lib/directive/link-permissions.directive.ts
> +  private andOperator: boolean = false;
always the same ;-) And now the joke (in French) :
 
"Tu sais pourquoi Mickey Mousse ? parce que Mario Brosse !"

2022-11-02 14:35 UTC, zannkukai commented on projects/shared/src/lib/service/permissions.service.ts
> +    return this;
remove blank line.
Are you sure about return statement ? maybe `return this._permissions` ?

2022-11-02 14:35 UTC, zannkukai commented on projects/shared/src/lib/service/permissions.service.ts
> +  private permissions = new Set<string>();
add "_" for private variable

2022-11-02 14:35 UTC, zannkukai commented on projects/shared/src/lib/service/permissions.service.ts
> +   canAccess(permission: string | string[], and: boolean = false): boolean {
It's here the core of MY "andOperator" problem. If you change `and: boolean` by `operator: string = 'or'`, you could much more flexible if necessary in next PR's/US.

2022-11-02 14:35 UTC, zannkukai commented on projects/shared/src/lib/service/permissions.service.ts
> +      : permission.some((perm: string) => this.permissions.has(perm))
use a switch to implement as many operator as you want
```
swtich (operator) {
    case 'and': 
        return permission.every((perm: string) => this.permissions.has(perm))
    case 'or': 
        return permission.some((perm: string) => this.permissions.has(perm))
    case 'xor':
        ... # should not be implemented at this time ;-)
    default:
        throw new Exception("invalid operator")

2022-11-02 14:35 UTC, zannkukai commented on projects/shared/src/lib/service/user.service.ts
> +          loggedUser.permissions.push(PERMISSIONS.PTRN_ACCESS);
Seems use for TEST & debug, Must be removed

2022-11-03 07:09 UTC, Garfield-fr commented on projects/admin/src/app/circulation/circulation-routing.module.ts
> +        canActivate: [ PermissionGuard ], data: { permissions: [ PERMISSIONS.CIRC_ADMIN ] }
When there are children, the parent route is never used

2022-11-03 07:19 UTC, Garfield-fr commented on projects/admin/src/app/menu/service/menu-user-services.service.ts
> +      const importFromWebMenu = catalogMenu.addChild('Import from the web')
Changed with `doc-create`

2022-11-03 07:20 UTC, Garfield-fr commented on projects/admin/src/app/menu/service/menu-user-services.service.ts
> +      if (this._permissionsService.canAccess(PERMISSIONS.ITEM_ACCESS)) {
It is in the planning to put other menu lines.

2022-11-23 13:09 UTC, zannkukai approved these changes
There is yet many `if` statement into `[menu-user-services.service.ts](https://github.com/rero/rero-ils-ui/pull/904/files#diff-1f81d18441a4bf8ce4ced540eb343d9464cbe66f2c5681b657c44663a15a0f99)`. Are they removed in next PR (including the recursing function ?)

2022-12-06 11:39 UTC, merged