statistics: library statistics charts
rero/rero-ils-ui pull request #943
Opened 2023-02-23 08:30 UTC by zannkukai

* Creates a module for statistic charts.
* Creates library circulation operations chart + admin widget/
* Creates document type repartition chart.

## Dependencies

* https://github.com/rero/rero-ils/pull/3243

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2023-05-30 13:41 UTC, lauren-d requested changes

2023-05-30 13:41 UTC, lauren-d commented on projects/admin/src/environments/environment.ts
> +  ngxChartsColorScheme: 'nightLights'  //https://github.com/swimlane/ngx-charts/blob/master/projects/swimlane/ngx-charts/src/lib/utils/color-sets.ts
You need to apply this change in 'environment.prod.ts' too

2023-06-07 13:09 UTC, Garfield-fr commented on projects/admin/src/app/widgets/statistics-charts/utils.ts
> +  return year + '-' + month + '-' + day;
suggestion: `[year, month, day].join('-')`

2023-06-07 13:11 UTC, Garfield-fr commented on projects/admin/src/app/widgets/statistics-charts/components/library/circulation-rate-operation-chart/circulation-rate-operation-chart.component.ts
> +        })  // TODO :: remove sample data to debug
xxxApiService ?

2023-06-07 13:13 UTC, Garfield-fr commented on projects/admin/src/app/widgets/statistics-charts/components/library/circulation-operation-chart/circulation-operation-chart.component.ts
> +      .getCirculationStatistics(this.libraryPid, this.settings.statisticsFilters);
xxxApiService ?

2023-06-07 13:14 UTC, Garfield-fr commented on projects/admin/src/app/widgets/statistics-charts/components/library/document-repartition-chart/document-repartition-chart.component.ts
> +    return this._statService.getDocTypeRepartitionStatistics(this.libraryPid);
xxxApiService ?

2023-07-06 07:23 UTC, ManaDeweerdt commented
- [ ] cannot select a date clicking on the calendar icon (but can change the date in the box > ok).

2024-04-02 09:21 UTC, closed without merging