library switch menu: fix sort by name
rero/rero-ils-ui pull request #970
Opened 2023-04-12 10:37 UTC by Garfield-fr

* Closes rero/rero-ils#2397.

2023-04-12 14:48 UTC, zannkukai requested changes

2023-04-12 14:48 UTC, zannkukai commented on projects/admin/src/app/menu/service/library-switch-menu.service.ts
> +          return first.name >= second.name ? 1 : -1
you should use `localeCompare` function to compare string.
`return fist.name.localeCompare(second.name)`
Also, it's convenient to use "a" & "b" as variable name for comparaison methods.

2023-04-13 08:19 UTC, PascalRepond commented
This sorts the libraries by `library.name`, the issue specifies to sort them by `library.code`.

2023-04-13 09:07 UTC, Garfield-fr commented
> This sorts the libraries by `library.name`, the issue specifies to sort them by `library.code`.

My bad. I corrected by sorting on the code.

2023-04-13 09:10 UTC, PascalRepond approved these changes

2023-04-14 06:48 UTC, zannkukai approved these changes

2023-04-18 08:31 UTC, lauren-d approved these changes

2023-04-18 08:41 UTC, merged