operation log: add library name after operator
rero/rero-ils-ui pull request #972
Opened 2023-04-12 14:06 UTC by Garfield-fr

* Closes rero/rero-ils#2059.

### Dependencies
- https://github.com/rero/rero-ils/pull/3311

2023-04-12 14:55 UTC, zannkukai reviewed
How are you sure than `metadata.library` is the selected switchLibrary entry at the moment of the operation ? 

As an exemple: 
* logged as Astrid working on AOSTE1
* Edit an item of AOASTE1, switch location to "AOSTE2.any_location"
* The opLog.metadata.library will be "AOSTE2", but the operation was made by "Astrid logged on AOSTE1"

As the switchLibrary entry is not a value known by the backend, it can't be exploited.
For me the original issue cannot be solved in current system implementation

2023-04-13 06:13 UTC, PascalRepond commented
> As the switchLibrary entry is not a value known by the backend, it can't be exploited. For me the original issue cannot be solved in current system implementation

Exactly, the switch library is known only by the frontend. This causes multiple problems, also for stats of created resources because we don't know the library for librarians with multiple libraries. However, this implementation should be acceptable at the moment as librarians with multiple libraries are an exception. But we should think about how to make it cleaner.

2023-04-13 08:35 UTC, PascalRepond requested changes
- [x] Displaying document operation logs containing librarians from another organisation results in 403 errors because of permissions

2023-04-14 07:10 UTC, zannkukai commented
> However, this implementation should be acceptable at the moment as librarians with multiple libraries are an exception. But we should think about how to make it cleaner.

We know this solution isn't a complete and valid solution but it's correct : Work now, and in some weeks work again ... 
Or maybe try to find a complete solution (and more time consuming) now and take a coffee in some weeks.
As it seems not a critical issue at this time, my opinion is to find a complete solution now.

2023-04-14 09:39 UTC, PascalRepond commented
> We know this solution isn't a complete and valid solution but it's correct : Work now, and in some weeks work again ... Or maybe try to find a complete solution (and more time consuming) now and take a coffee in some weeks. As it seems not a critical issue at this time, my opinion is to find a complete solution now.

This would be scope creep in my opinion. This issue addresses a small and specific demand. Although a larger problem (`patron.library`: https://github.com/rero/rero-ils/issues/3310) has an influence on this, this doesn't mean that we have to fix everything at the same time. Issue 3310 should be addressed in time when it has been more precisely specified.

2023-04-17 13:07 UTC, PascalRepond approved these changes

2023-04-18 08:29 UTC, lauren-d approved these changes

2023-04-18 08:29 UTC, lauren-d commented on projects/admin/src/app/record/operation-logs/operation-logs.component.html
> +      <ng-container *ngIf="metadata.library">- {{ metadata.library.name }}</ng-container>
COSMETIC: Is there a missing space before the hyphen ? 
`- {{ metadata.library.name }}` or ` - {{ metadata.library.name }}`

2023-04-18 08:41 UTC, ManaDeweerdt commented
- [ ] In case of Astrid with multiple login location, the operation log will always be 'Bibliothèque de la Vallée d'AOSTE', no matter what login location. It should be the login location.
![image](https://user-images.githubusercontent.com/12396034/232719625-6ad458af-22b0-49c0-b9e2-9cb0060e65ff.png)

2023-04-18 12:42 UTC, benerken requested changes
Thanks for this PR but it will create another issue for users with multiple libraries. Sorry but it's not the solution to solve an issue for one kind of users and let down the others.

2023-04-27 13:30 UTC, merged